.gitignore
bots/define/requirements.txt

Same two commits as those merged yesterday in Eeshan's repository. Should be good to merge.

Initial Fixes

---

zulip_bots/zulip_bots/bots/weather/weather.py

This small change provides a fix for #31.

weather bot: Amend temperature formatting.

---

zulip_bots/zulip_bots/bots/john/john.py
zulip_bots/zulip_bots/lib.py
zulip_botserver/zulip_botserver/server.py

This finalizes #9 .
@sampritipanda

bots: Add a restricted open function.

---

zulip_bots/zulip_bots/run.py

'bot_name' variable in line number 111 in run.py undefined.

bots: Fix 'run.py' file to run bots.

---

zulip_bots/zulip_bots/bots/googlesearch/googlesearch.py

I think that this one is a very high utility bot and needs to be worked upon.
I have made the changes in separate commit as I am not sure if we want to go ahead with the second one right now.
The first commit is just reverting the googlesearch.py file back to its original state (mistakenly changed by someone)
The second commit makes it python 2.x compatible.

Clean up googlesearch bot.

---

tools/test-bots

bot tests: Make test-bots fail with proper exit code.

---

tools/lint

This might lead to a couple PRs failing that are currently not.

testing: Make linter fail with exit code if any check fails.

---

README.md
tools/provision

This PR
* refactors script variables and checks for Windows/Linux differences in a more robust way.
* dynamically names the venv with the pattern <zulip-api-py<PYVERSION>-venv> and allows users to specify custom python versions.

Refactor provision script.

---

zulip/zulip/__init__.py

Resolves #86 
Be free, my tiny patch!

set event_types to empty list if not supplied in register

---

zulip/README.md
zulip/integrations/zephyr/sync-public-streams
zulip/integrations/zephyr/zephyr_mirror_backend.py
zulip/setup.py
zulip/zulip/__init__.py

This removes the simplejson dependency.

zulip: Move from simplejson to json.

---

zulip_botserver/tests/server_test_lib.py
zulip_botserver/tests/test_server.py
zulip_botserver/zulip_botserver/server.py

zulip_botserver: Don't reinstantiate ExternalBotHandlers.

---

zulip_bots/zulip_bots/bots/xkcd/test_xkcd.py
zulip_bots/zulip_bots/bots/xkcd/xkcd.py

zulip_bots: Make xkcd bot error more verbose.

---

zulip/zulip/__init__.py
zulip_bots/zulip_bots/bots/incrementor/incrementor.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py
zulip_bots/zulip_bots/bots/virtual_fs/virtual_fs.py
zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/test_lib.py
zulip_botserver/tests/test_server.py

This depends on [zulip/#7227](https://github.com/zulip/zulip/pull/7227)

bots: Access state in external Zulip server.

---

tools/provision

@showell can you test this with Py 2 and 3?

Fix provisioning Python version mixup.

---

zulip_bots/zulip_bots/bots/incrementor/incrementor.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py
zulip_bots/zulip_bots/bots/virtual_fs/virtual_fs.py
zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/test_lib.py

zulip_bots: Only cache storage.get(). Don't cache put().

---

zulip/zulip/__init__.py
zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/test_lib.py

We still need to make a full rename from state to storage, this is just to get the system working again.

Rename bot storage endpoint from state to storage.

---

.travis.yml
tools/test-py2-legacy-support
zulip_bots/zulip_bots/bots/giphy/fixtures/test_403.json
zulip_bots/zulip_bots/bots/giphy/fixtures/test_no_result.json
zulip_bots/zulip_bots/bots/giphy/fixtures/test_normal.json
zulip_bots/zulip_bots/bots/giphy/giphy.py
zulip_bots/zulip_bots/bots/giphy/test_giphy.py
zulip_bots/zulip_bots/bots/yoda/yoda.py
zulip_bots/zulip_bots/test_lib.py

This comes along with a few improvements to the testing system (and bot improvements).

Get 100% test coverage for Giphy bot.

---

zulip_bots/zulip_bots/test_lib.py

This is a (further-reduced) port of zulip/zulip#5587 in the main zulip repo, but focused on only testing multiple responses from single messages. For example, a message might cause the bot to respond to the sender with a confirmation message, a group message and even one to one (or more) admins/maintainers/moderators. It originated from wanting to test the 'pollbot' I wrote (not yet merged, zulip/zulip#5426 in main zulip tracker).
As it stands, the PR should enable all bots to continue to pass tests, though the testing does pass through the new/adjusted code. As such, I've only extended the interface for testing bots to allow testing multiple responses, but if this code is considered suitable then it seems reasonable to switch to switching from `assert_bot_response` to …

bot testing: Improve failure output & add testing of multiple responses

---

tools/run-mypy
tools/test-lib
zulip_bots/zulip_bots/lib_tests.py

This starts to add direct test coverage on
zulip_bots/zulip_bots/lib.py.
It is not yet integrated into tools/test-main.

Add tools/test-lib.

---

tools/test-bots
zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py
zulip_bots/zulip_bots/bots/helloworld/test_helloworld.py
zulip_bots/zulip_bots/bots/help/test_help.py
zulip_bots/zulip_bots/bots/incrementor/test_incrementor.py
zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py
zulip_bots/zulip_bots/test_lib.py

This is still a work in progress.

Move tests toward more transparent stubbing.

---

tools/run-mypy
tools/test-py2-legacy-support
zulip_bots/zulip_bots/bots/helloworld/helloworld.py
zulip_bots/zulip_bots/bots/helloworld/test_helloworld.py

This is a sample PR for the GCI task mypy-annotations Type B.

Add mypy annotations for hello world bot.

---

zulip_bots/zulip_bots/bots/giphy/test_giphy.py
zulip_bots/zulip_bots/test_lib.py

This also adds a couple tiny patches to StubBotTestCase and StubBotHandler.

Simplify test_giphy.py

---

tools/run-mypy
zulip_bots/zulip_bots/bots/github_detail/github_detail.py
zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py
zulip_bots/zulip_bots/bots/googlesearch/googlesearch.py
zulip_bots/zulip_bots/bots/googlesearch/test_googlesearch.py
zulip_bots/zulip_bots/bots/help/help.py
zulip_bots/zulip_bots/bots/help/test_help.py

This adds mypy annotations for:
github_detail
googlesearch
help

mypy: Add annotations for bots.

---

zulip_bots/zulip_bots/bots/giphy/test_giphy.py
zulip_bots/zulip_bots/bots/googlesearch/fixtures/test_attribute_error.json
zulip_bots/zulip_bots/bots/googlesearch/fixtures/test_ignore_links.json
zulip_bots/zulip_bots/bots/googlesearch/googlesearch.py
zulip_bots/zulip_bots/bots/googlesearch/test_googlesearch.py
zulip_bots/zulip_bots/bots/googletranslate/test_googletranslate.py

Fixed issue where giphy posts error to console on test
Removed redundant code in googlesearch
Made googlesearch & googletranslate have 100% test coverage

Fixed several issues with giphy & googlesearch, and increased test coverage

---

zulip_bots/zulip_bots/bots/wikipedia/fixtures/test_multi_word.json
zulip_bots/zulip_bots/bots/wikipedia/fixtures/test_number_query.json
zulip_bots/zulip_bots/bots/wikipedia/fixtures/test_single_word.json
zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py
zulip_bots/zulip_bots/bots/wikipedia/wikipedia.py

Improved response, now returns top 3 results, fixed tests.

---

zulip_bots/zulip_bots/bots/wikipedia/doc.md
zulip_bots/zulip_bots/bots/wikipedia/fixtures/test_status_code.json
zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py
zulip_bots/zulip_bots/test_lib.py

I added the documentation file, and obtained 100% test coverage for the wikipedia bot. I suspect that I made some stylistic error along the way, so let me know how to make the changes perfect!

interactive bots: Improve wikipedia bot.

---

zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py

* Add additional tests
* Refactor to remove unnecessary code, migrate to python3, separate game logic & responses

[WIP] Tictactoe refactoring

---

.editorconfig

This is a new file for this repo, but taken from the amended file presented in zulip/zulip#7806 (adding .pyi support).

Editing: Add .editorconfig from zulip/zulip (with note).

---

zulip_bots/zulip_bots/bots/github_detail/github_detail.py
zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py

Fixes #172 
Also Added a test to verify the same.

github_detail: Limit bot to 5 requests per message.  Fixes #172 .

---

zulip_bots/zulip_bots/bots/connect_four/connect_four.py
zulip_bots/zulip_bots/bots/connect_four/controller.py
zulip_bots/zulip_bots/bots/connect_four/doc.md
zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py

The Connect Four bot allows players to play against either the computer or another player via a well-controlled series of private messages. 80% code coverage was acquired by the tests

interactive bots: Create connect four bot

---

zulip_bots/zulip_bots/bots/connect_four/connect_four.conf
zulip_bots/zulip_bots/bots/connect_four/connect_four.py
zulip_bots/zulip_bots/bots/connect_four/controller.py
zulip_bots/zulip_bots/bots/connect_four/doc.md
zulip_bots/zulip_bots/bots/connect_four/game_adapter.py
zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py

These changes address @showell requests to create a general game framework, by introducing a GameAdapter class that can be easily used to create bots that manage single player and two player games. The class currently is located within the connect_four bot's folder, although it should eventually be moved to another folder to allow any bot to use it. 
The changes also allow superusers to be added to the config file. These 'superusers' are moderators who can reset the bot in case users abuse the fact that the bot can only handle a single game at a time.

Improve connect four bot

---

zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py

Issue #171 
Update `baremetrics.py`.

zulip_bots: Check API key on initialization for Baremetrics bot.

---

zulip_bots/zulip_bots/bots/mention/mention.conf
zulip_bots/zulip_bots/bots/mention/mention.py

Issue #171 
Updated `mention.py` -> added the required code.
Updated `mention.py` -> reformatted the existing code.
Updated `mention.conf` -> removed comment as some INI parsers don't support comments.

zulip_bots: Check Access Token on initialization for Mention bot.

---

zulip_bots/zulip_bots/bots/baremetrics/fixtures/list_customers.json
zulip_bots/zulip_bots/bots/baremetrics/fixtures/list_plans.json
zulip_bots/zulip_bots/bots/baremetrics/fixtures/list_subscriptions.json
zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py

Improve tests for Baremetrics bot.

---

tools/custom_check.py
tools/provision
tools/test-bots
tools/test-lib

@roberthoenig Please feel free to merge this if it builds.

bots: Finish py2 -> py3 tasks for now.

---

zulip/integrations/codebase/zulip_codebase_mirror
zulip/integrations/git/zulip_git_config.py
zulip/integrations/google/get-google-credentials
zulip/integrations/openshift/zulip_openshift_config.py
zulip/integrations/trac/zulip_trac.py
zulip/integrations/zephyr/sync-public-streams
zulip/integrations/zephyr/zephyr_mirror_backend.py
zulip/zulip/__init__.py
zulip/zulip/examples/upload-file
zulip_bots/zulip_bots/bots/chess/chess.py
zulip_bots/zulip_bots/bots/dialogflow/test_dialogflow.py
zulip_bots/zulip_bots/bots/witai/witai.py
zulip_bots/zulip_bots/bots/youtube/youtube.py
zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/request_test_lib.py
zulip_bots/zulip_bots/run.py
zulip_bots/zulip_bots/terminal.py
zulip_bots/zulip_bots/test_lib.py
zulip_botserver/tests/server_test_lib.py

Strict optional mypy patches without tool change from #250

---

zulip_bots/zulip_bots/bots/monkeytestit/doc.md
zulip_bots/zulip_bots/bots/monkeytestit/fixtures/website_result_fail.json
zulip_bots/zulip_bots/bots/monkeytestit/fixtures/website_result_success.json
zulip_bots/zulip_bots/bots/monkeytestit/lib/extract.py
zulip_bots/zulip_bots/bots/monkeytestit/lib/parse.py
zulip_bots/zulip_bots/bots/monkeytestit/lib/report.py
zulip_bots/zulip_bots/bots/monkeytestit/monkeytestit.conf
zulip_bots/zulip_bots/bots/monkeytestit/monkeytestit.py
zulip_bots/zulip_bots/bots/monkeytestit/test_monkeytestit.py

[Link to GCI task](https://codein.withgoogle.com/dashboard/task-instances/6000511457165312/)

interactive bots: Create monkeytest.it bot.

---

zulip_bots/zulip_bots/bots/baremetrics/fixtures/test_key_error.json
zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py
zulip_bots/zulip_bots/bots/mention/test_mention.py
zulip_bots/zulip_bots/bots/yoda/fixtures/test_api_key_error.json
zulip_bots/zulip_bots/bots/yoda/fixtures/test_service_unavailable_error.json
zulip_bots/zulip_bots/bots/yoda/fixtures/test_unknown_error.json
zulip_bots/zulip_bots/bots/yoda/test_yoda.py
zulip_bots/zulip_bots/bots/yoda/yoda.py

Improve test coverage for Zulip Bots.

---

zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py
zulip_bots/zulip_bots/bots/baremetrics/fixtures/create_plan.json
zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py

I went ahead and added a feature to the Baremetrics bot because I felt that it was lacking and I had a bit of downtime between GCI tasks.

Enhance Baremetrics bot

---

zulip_bots/zulip_bots/bots/converter/test_converter.py

Added a few test cases to reach 100% test coverage on converter bot.
Fixes #122

converter bot: Reached 100% test coverage

---

zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py
zulip_bots/zulip_bots/bots/virtual_fs/test_virtual_fs.py

Improve test_coverage for github-detail bot

---

zulip_bots/zulip_bots/bots/dropbox_share/doc.md
zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.conf
zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.py
zulip_bots/zulip_bots/bots/dropbox_share/requirements.txt
zulip_bots/zulip_bots/bots/dropbox_share/test_dropbox_share.py
zulip_bots/zulip_bots/bots/dropbox_share/test_util.py

A ton of features can still be added to this bot.
I am working on test cases.

Create Dropbox bot to do primary file operations.

---

zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py
zulip_bots/zulip_bots/game_handler.py

Allow a game to start even if `max_players` is not reached.
Adding a new command `play game` to start a game if the
number of players is between max and min no. of players.

Make `game_handler` support starting a game with a range of players.

---

tools/run-mypy
zulip_bots/zulip_bots/bots/susi/fixtures/test_reply.json
zulip_bots/zulip_bots/bots/susi/susi.py
zulip_bots/zulip_bots/bots/susi/test_susi.py

This bot uses SUSI_SERVER API to get response.

Susi AI Bot: Create a susi ai bot.

---

zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py
zulip_bots/zulip_bots/bots/baremetrics/fixtures/create_plan_error.json
zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py
zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py
zulip_bots/zulip_bots/bots/link_shortener/fixtures/test_invalid_key.json
zulip_bots/zulip_bots/bots/link_shortener/test_link_shortener.py
zulip_bots/zulip_bots/test_lib.py

#122 Coverage 100% for link_shortener

bot testing : 100% test coverage 

---

zulip_bots/zulip_bots/bots/connect_four/connect_four.py
zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py

#329 
Please review I did a small change to connect four to allow shorthand moves with regex. Should I do this for other game bots and are tests required for this?

game_handler : Add shorthand moves

---

zulip_bots/zulip_bots/bots/stack_overflow/doc.md
zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_incorrect_query.json
zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_multi_word.json
zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_number_query.json
zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_single_word.json
zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_status_code.json
zulip_bots/zulip_bots/bots/stack_overflow/requirements.txt
zulip_bots/zulip_bots/bots/stack_overflow/stack_overflow.py
zulip_bots/zulip_bots/bots/stack_overflow/test_stack_overflow.py

Added bot to answer queries using StackOverflow API

stack_overflow bot  : Add StackOverflow bot.

---

zulip_bots/zulip_bots/bots/twitpost/Readme.md
zulip_bots/zulip_bots/bots/twitpost/fixtures/api_response.json
zulip_bots/zulip_bots/bots/twitpost/test_twitpost.py
zulip_bots/zulip_bots/bots/twitpost/twitpost.py
zulip_bots/zulip_bots/bots/twitpost/twitter.ini

This bot makes it possible to tweet on twitter from Zulip chat itself.
Discussion:
https://chat.zulip.org/#narrow/stream/127-integrations/topic/adding.20a.20bot
https://chat.zulip.org/#narrow/stream/127-integrations/topic/hackathon.20bots

Add twitpost bot.

---

zulip_bots/zulip_bots/bots/connect_four/connect_four.py
zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
zulip_bots/zulip_bots/bots/game_handler_bot/game_handler_bot.py
zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py
zulip_bots/zulip_bots/bots/gameoffifteen/gameoffifteen.py
zulip_bots/zulip_bots/bots/gameoffifteen/test_game_of_fifteen.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py
zulip_bots/zulip_bots/game_handler.py

This PR adds first single player game bot, which is game of fifteen. Also, it enforces the 'rules' command for this game as well as previous games. This PR also adds some basic functionality and customization in game_handler.py to support single player games. 
The tests are yet to be added, so it's WIP.

Add game of fifteen bot.

---

tools/deploy

Issue [#338](https://github.com/zulip/python-zulip-api/issues/338).
@aero31aero, please review this.

tools/deploy: Annotate tools/deploy using mypy

---

tools/deploy

Add `tools/deploy delete` to cleanly stop and delete the docker container and image, as well as the source files for the image (according to #338)
Related with [PR in zulip-botmatrix](https://github.com/aero31aero/zulip-botmatrix/pull/5)

#338 Add `tools/deploy delete` command.

---

tools/deploy

Related to [PR in zulip-botmatrix](https://github.com/aero31aero/zulip-botmatrix/pull/11)

deploy: Support new JSON-formatted responses from Botfarm.

---

zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/lib_tests.py

Change StateHandler implementation to the following:
- do not fetch state in `__init__()`;
- fetch every key only once on demand and cache it.
Fixes #359

#359 Make StateHandler lazy and only do `get` one key at a time

---

zulip_botserver/tests/server_test_lib.py
zulip_botserver/tests/test_server.py
zulip_botserver/zulip_botserver/server.py

zulip_botserver: Do some cleanup

Cleanup and style

---

zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py
zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py
zulip_bots/zulip_bots/bots/helloworld/helloworld.py
zulip_bots/zulip_bots/bots/idonethis/idonethis.py
zulip_bots/zulip_bots/bots/idonethis/test_idonethis.py
zulip_bots/zulip_bots/bots/mention/mention.py
zulip_bots/zulip_bots/bots/salesforce/salesforce.py
zulip_bots/zulip_bots/bots/stack_overflow/stack_overflow.py
zulip_bots/zulip_bots/bots/trello/test_trello.py
zulip_bots/zulip_bots/bots/trello/trello.py

This PR started off intending to clarify some typing, and ended up in some tidying of the code and tests as I got carried away; these primarily increase legibility and removal of repeated code.
I also found a suspected bug in the baremetrics output, as per the added comment line, namely a switch of name and display_name, which was revealed by use of the `dict` style formatting.

Bots: Improve typing & code in various bots

---

zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py

bots: Add proper error handling for trivia bot.

---

tools/provision
zulip_bots/setup.py
zulip_bots/zulip_bots/bots/baremetrics/requirements.txt
zulip_bots/zulip_bots/bots/beeminder/requirements.txt
zulip_bots/zulip_bots/bots/define/requirements.txt
zulip_bots/zulip_bots/bots/flock/requirements.txt
zulip_bots/zulip_bots/bots/giphy/requirements.txt
zulip_bots/zulip_bots/bots/github_detail/requirements.txt
zulip_bots/zulip_bots/bots/google_search/requirements.txt
zulip_bots/zulip_bots/bots/google_translate/requirements.txt
zulip_bots/zulip_bots/bots/jira/requirements.txt
zulip_bots/zulip_bots/bots/link_shortener/requirements.txt
zulip_bots/zulip_bots/bots/mention/requirements.txt
zulip_bots/zulip_bots/bots/monkeytestit/requirements.txt
zulip_bots/zulip_bots/bots/stack_overflow/requirements.txt
zulip_bots/zulip_bots/bots/trello/requirements.txt
zulip_bots/zulip_bots/bots/trivia_quiz/requirements.txt
zulip_bots/zulip_bots/bots/weather/requirements.txt
zulip_bots/zulip_bots/bots/wikipedia/requirements.txt
zulip_bots/zulip_bots/bots/xkcd/requirements.txt
zulip_bots/zulip_bots/bots/yoda/requirements.txt
zulip_bots/zulip_bots/bots/youtube/requirements.txt

zulip_bots: Clean up the bots dependency installation process.

---

zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.py
zulip_bots/zulip_bots/bots/dropbox_share/test_dropbox_share.py

#122 Get `dropbox_share` bot to 100% test coverage 

---

zulip_bots/zulip_bots/bots/trivia_quiz/test_trivia_quiz.py
zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py

I have introduced two variables `answered_options` and `ended` in the bot storage. Initially `ended` is set to False. 
When we have start answering, the options we answer are stored in `answered_options`. After three wrong failure we get the message `Three failed attempts at <quiz_id>:disappointed:\nThe correct answer is <answer>." at three wrong answers.`. After that, `ended` is being set to `True`. 
Now if the user continues playing with the same question, they won't get the three failed attempts message, and they can continue answering the question.
Hence we would receive the 3-failed attempts message from the bot only for the first time.

bots: Improve response at 3 wrong answers in trivia bot.

---

zulip/zulip/__init__.py
zulip/zulip/examples/get-messages

**Testing plan:** lint and mypy checks passed.

api: Implement GET /messages.

---

zulip_bots/zulip_bots/bots/front/fixtures/archive.json
zulip_bots/zulip_bots/bots/front/fixtures/archive_error.json
zulip_bots/zulip_bots/bots/front/fixtures/comment.json
zulip_bots/zulip_bots/bots/front/fixtures/comment_error.json
zulip_bots/zulip_bots/bots/front/fixtures/delete.json
zulip_bots/zulip_bots/bots/front/fixtures/delete_error.json
zulip_bots/zulip_bots/bots/front/fixtures/open.json
zulip_bots/zulip_bots/bots/front/fixtures/open_error.json
zulip_bots/zulip_bots/bots/front/fixtures/spam.json
zulip_bots/zulip_bots/bots/front/fixtures/spam_error.json
zulip_bots/zulip_bots/bots/front/test_front.py

#122 Get `front` bot to 100% test coverage

---

zulip/zulip/__init__.py
zulip/zulip/examples/delete-message

api: Implement DELETE /messages/<message_id>.

---

zulip/zulip/__init__.py
zulip/zulip/examples/get-raw-message

api: Implement GET /messages/<message_id>.

---

zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py

Increase test coverage for `tictactoe` bot

---

zulip/zulip/__init__.py
zulip/zulip/examples/message-history

 api: Implement GET /messages/<message_id>/history.

---

zulip_bots/zulip_bots/bots/jira/fixtures/test_create.json
zulip_bots/zulip_bots/bots/jira/fixtures/test_create_error.json
zulip_bots/zulip_bots/bots/jira/fixtures/test_edit.json
zulip_bots/zulip_bots/bots/jira/fixtures/test_edit_error.json
zulip_bots/zulip_bots/bots/jira/fixtures/test_get.json
zulip_bots/zulip_bots/bots/jira/fixtures/test_get_error.json
zulip_bots/zulip_bots/bots/jira/jira.py
zulip_bots/zulip_bots/bots/jira/test_jira.py
zulip_bots/zulip_bots/request_test_lib.py

Related to #122.
Also made some refactoring for old tests.

#122 Get `jira` bot to 100% test coverage

---

zulip_bots/zulip_bots/bots/flock/fixtures/test_found_invalid_recipient.json
zulip_bots/zulip_bots/bots/flock/fixtures/test_no_recipient_found.json
zulip_bots/zulip_bots/bots/flock/flock.py
zulip_bots/zulip_bots/bots/flock/test_flock.py

Related to #122.
Also made some refactoring of bot's implementation.

#122 Get `flock` bot to 100% test coverage

---

zulip_bots/zulip_bots/bots/giphy/test_giphy.py

#122 Get `giphy` bot to 100% test coverage

---

zulip_bots/zulip_bots/bots/youtube/fixtures/test_unknown_error.json
zulip_bots/zulip_bots/bots/youtube/test_youtube.py

#122 Get `youtube` bot to 100% test coverage

---

zulip/zulip/__init__.py
zulip/zulip/examples/update-flags

api: Implement POST /messages/flags.

---

zulip/zulip/__init__.py
zulip/zulip/examples/realm-emoji

api: Implement GET /realm/emoji.

---

zulip/zulip/examples/update-message-flags

api: Rename update-flags to update-message-flags.

---

zulip_bots/zulip_bots/bots/merels/libraries/game.py
zulip_bots/zulip_bots/bots/merels/merels.py
zulip_bots/zulip_bots/bots/merels/test/test_database.py
zulip_bots/zulip_bots/bots/merels/test/test_game.py
zulip_bots/zulip_bots/bots/merels/test/test_mechanics.py
zulip_bots/zulip_bots/bots/merels/test_merels.py

I have made revisions to the Merels Bot test codes.  Most of the code for the game is tested in the tests folders within merels.  `test_merels.py`essentially tests if the interaction with the game_handler module is fine.

[WIP] Updating Tests for Merels Bot

---

zulip/zulip/__init__.py
zulip/zulip/examples/mute-topic

api: Implement PATCH /users/me/subscriptions/muted_topics.

---

zulip/zulip/__init__.py
zulip/zulip/examples/alert-words

**Testing plan:** lint and mypy checks passed locally. Ran all the possible combinations of the example.

api: Implement /users/me/alert_words.

---

zulip/zulip/__init__.py

**Testing plan:** lint and mypy checks passed locally. Tested the example in Python's REPL interpreter.

api: Implement POST /typing.

---

zulip/zulip/__init__.py

**Testing plan:** lint and mypy checks passed locally. Tested the example in Python's REPL interpreter.

api: Implement POST /mark_(all|stream|topic)_as_read.

---

zulip/zulip/__init__.py

**Testing plan:** lint and mypy checks passed locally. Tested the example in Python's REPL interpreter.

api: Implement PATCH /settings/notifications.

---

zulip/zulip/__init__.py
zulip/zulip/examples/delete-stream

**Testing plan:** lint and mypy checks passed locally. Tested the example script with success.

api: Implement DELETE /streams/<stream_id>.

---

zulip/zulip/__init__.py

Added binding for `/user_groups` endpoint

api: Implement GET /user_groups.

---

README.md

I'm new and trying to figure out how to help...
Spell check is the best I've got right now.

The word run was written twice

---

zulip/zulip/__init__.py

**Testing plan**: lint and mypy checks passed locally.
This PR is based on the PRs made by @YagoGG, so please let me know if there's is anything left to do here.

api: Implement endpoint to upload custom emoji.

---

zulip_bots/zulip_bots/bots/github_detail/doc.md
zulip_bots/zulip_bots/bots/xkcd/doc.md

Linked to the first commit from https://github.com/zulip/zulip/pull/12548.

docs: Change integration docs for portico/integrations

---

zulip_bots/zulip_bots/bots/define/define.py
zulip_bots/zulip_bots/bots/define/fixtures/test_incorrect_word.json
zulip_bots/zulip_bots/bots/define/fixtures/test_multi_type_word.json
zulip_bots/zulip_bots/bots/define/fixtures/test_single_type_word.json

v2 of Owlbot changes key "defeniton" to "definition", so make changes in bot and tests accordingly.
Solves issue #527 .

Bots: Update Owlbot endpoint from v1 to v2.

---

zulip/zulip/__init__.py

api: Fix undefined variable reference from previous commit.

---

.travis.yml
zulip/setup.py
zulip_bots/setup.py
zulip_botserver/setup.py

@timabbott: FYI :) I can make a release after you merge this.

pypi: Add support for Python 3.8.

---

zulip/integrations/bridge_with_irc/irc_mirror_backend.py

bridge_with_irc: Check if bot is subscribed to stream at startup.

---

zulip_bots/zulip_bots/bots/connect_four/connect_four.py
zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py
zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py
zulip_bots/zulip_bots/game_handler.py

Some of the emojis that the tictactoe and connect_four bots were using were removed
I've replaced them with alternative existing emojis
The bots also say `You cannot play against the computer in this game.` even if you can. This has also been fixed

bots: Fix tictactoe, connect_four emoji and computer play message

---

tools/custom_check.py

https://chat.zulip.org/#narrow/stream/127-integrations/topic/python-zulip-api.20to.20use.20python3/near/846057

lint: Remove explicit python invocation check.

---

zulip/integrations/bridge_between_zulips/run-interrealm-bridge
zulip/integrations/bridge_with_irc/irc-mirror.py
zulip/integrations/bridge_with_matrix/matrix_bridge.py
zulip/integrations/codebase/zulip_codebase_mirror
zulip/integrations/git/post-receive
zulip/integrations/google/get-google-credentials
zulip/integrations/google/google-calendar
zulip/integrations/hg/zulip_changegroup.py
zulip/integrations/jabber/jabber_mirror.py
zulip/integrations/jabber/jabber_mirror_backend.py
zulip/integrations/log2zulip/log2zulip
zulip/integrations/nagios/nagios-notify-zulip
zulip/integrations/openshift/post_deploy
zulip/integrations/perforce/git_p4.py
zulip/integrations/perforce/zulip_change-commit.py
zulip/integrations/rss/rss-bot
zulip/integrations/svn/post-commit
zulip/integrations/trello/zulip_trello.py
zulip/integrations/twitter/twitter-bot
zulip/integrations/zephyr/check-mirroring
zulip/integrations/zephyr/process_ccache
zulip/integrations/zephyr/sync-public-streams
zulip/integrations/zephyr/zephyr_mirror.py
zulip/integrations/zephyr/zephyr_mirror_backend.py

integrations: Migrate to Python 3.

---

zulip/zulip/__init__.py

This implements the GET /attachments endpoint.

api: Implement GET /attachments endpoint

---

zulip/zulip/__init__.py

This implements the /realm/presence api endpoint.

api: Implement GET /realm/presence endpoint.

---

zulip/zulip/__init__.py

This implements PATCH /users/{user_id} endpoint.

api: Implement PATCH /users/{user_id} endpoint

---

zulip/zulip/__init__.py

This implements POST /users/{user_id}/reactivate endpoint.

api: Implement POST /users/{user_id}/reactivate endpoint.

---

zulip/README.md
zulip/setup.py
zulip_bots/setup.py
zulip_botserver/setup.py

pypi: Prepare for the next major release.

---

zulip/zulip/__init__.py

This implements GET /messages/matches_narrow api endpoint.

api: Implement GET /messages/matches_narrow endpoint

---

zulip/zulip/__init__.py

This implements the POST /default_streams api endpoint.

api: Implement POST /default_streams api endpoint.

---

tools/release-packages
zulip/README.md

@timabbott: FYI :) I can make a release once this PR is merged.

pypi: More changes before the next major release.

---

zulip_bots/zulip_bots/lib.py
zulip_bots/zulip_bots/tests/test_lib.py

Refer to https://github.com/zulip/zulip/issues/14228 for more details. This PR addresses #551 and #552.

Bots in Group PMs

---

zulip/zulip/__init__.py

This adds api bindings for `/realm/profile_fields` and `/realm/profile_fields/{field_id}` endpoints.

api: Add bindings for /realm/profile_fields and /realm/profile_fields/{field_id} api endpoints.

---

zulip/zulip/__init__.py

This implements DELETE /realm/emoji/{emoji_name} api endpoint.

api: Implement DELETE /realm/emoji/{emoji_name}.

---

zulip/zulip/__init__.py

This implements GET /users/{user_id}/subscriptions/{stream_id} api endpoint.

api: Implement GET /users/{user_id}/subscriptions/{stream_id} endpoint.

---

zulip/zulip/__init__.py

Move a topic from one stream to another,
Example usage:
```python
>>> client.move_topic('stream_a', 'stream_b', 'my_topic')
{'result': 'success', 'msg': ''}
```

FEAT: add method to move topics between streams

---

zulip_botserver/README.md
zulip_botserver/tests/test_server.py
zulip_botserver/zulip_botserver/input_parameters.py
zulip_botserver/zulip_botserver/server.py

zulip-botserver: Allow passing config via environment variables

---

zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.py
zulip_bots/zulip_bots/bots/dropbox_share/requirements.txt
zulip_bots/zulip_bots/bots/dropbox_share/test_dropbox_share.py

Changes in dropox version >= 11.0 broke the dropbox bot.
The required fixes are mentioned at:
https://github.com/dropbox/dropbox-sdk-python/blob/main/UPGRADING.md#upgrading-from-v10xx-to-v1100

dropbox-bot: Update to support dropbox>=11.0.0.

---

tools/provision

Provision: Replace virtualenv by python native venv.

---

.github/workflows/zulip-tests.yml
tools/test-main.ps1

[As requested](https://github.com/zulip/python-zulip-api/pull/652#issuecomment-790871284)

ci: Setup Github Actions for Windows.

---

zulip/zulip/__init__.py

zulip: Add support for additional  args for call_on_each_*.

---

zulip/zulip/__init__.py

Fix Improper assignement of narrow variable outside its scope.

zulip: Fix call_on_each_event.

---

zulip_bots/zulip_bots/simple_lib.py
zulip_bots/zulip_bots/terminal.py

Fixes #686.
```
Enter your message: j
Reply from the bot is printed between the dotted lines:
-------
beep boop
-------
The bot reacts to message #1: wave
Enter your message: p
Reply from the bot is printed between the dotted lines:
-------
beep boop
-------
The bot reacts to message #3: wave
```

Implement react for TerminalBotHandler

---

zulip/setup.py

Address https://github.com/zulip/python-zulip-api/pull/663/files#r639104382.

Add click as req in setup.py for zulip-cli.

---

zulip_bots/zulip_bots/bots/incrementor/test_incrementor.py
zulip_bots/zulip_bots/simple_lib.py
zulip_bots/zulip_bots/terminal.py
zulip_bots/zulip_bots/test_lib.py

https://github.com/zulip/python-zulip-api/pull/688#issuecomment-847346061

Rename SimpleMessageServer and add documentation for TerminalBotHandler for clarity

---

zulip_bots/zulip_bots/bots/game_of_fifteen/doc.md

doc: Add doc.md for game_of_fifteen bot.

---

tools/test-bots

This test was fixed in commit ab97b37ce1d3075ed8fb9971abe776b7592297dc (#448).

test-bots: Remove merels exclusion

---

zulip/integrations/bridge_with_matrix/matrix_bridge.py
zulip/integrations/bridge_with_matrix/test_matrix.py

#702 hasn't been updated for a long time. #723 will take a while to finish. This PR remakes #702 so that the current bridge config can be more easily understood.

Clarify Matrix bridge terminology.

---

zulip/integrations/zephyr/check-mirroring
zulip/integrations/zephyr/zephyr_ctypes.py
zulip/integrations/zephyr/zephyr_mirror.py
zulip/integrations/zephyr/zephyr_mirror_backend.py

zephyr: Free received notices with ZFreeNotice

---

zulip_bots/zulip_bots/bots/youtube/youtube.py

youtube: Fix for HTTPError stub change
