.travis.yml, setup.py, tools/lint, tools/pep8.py, tools/server_lib/README.md, tools/server_lib/lister.py, tools/server_lib/printer.py, zulip/__init__.py
This particular commit should fail tests. I'll add another to fix them.
Results:
https://travis-ci.org/aero31aero/python-zulip-api/builds/250967292
```bash
1.72s$ tools/lint
pep8      | tools/lint:9:15: E225 missing whitespace around operator
pep8      | tools/lint:10:1: W191 indentation contains tabs
pep8      | tools/lint:10:5: E126 continuation line over-indented for hanging indent
pep8      | tools/lint:11:1: W191 indentation contains tabs
pep8      | tools/lint:12:1: W191 indentation contains tabs
pep8      | tools/lint:12:4: E126 continuation line over-indented for hanging indent
pep8      | tools/lint:16:1: W191 indentation contains tabs
pep8      | tools/lint:17:1: W191 indentation contains tabs
pep8      | tools/lint:17:5: E101 indentation contains mixed spaces and tabs
pep8 …
```
=> [WIP] Travis Support + Linting

zulip/zulip/__init__.py, zulip_bots/setup.py, zulip_botserver/setup.py
I just released all three of our pip packages:
* [zulip API bindings package](https://pypi.python.org/pypi/zulip)
* [zulip bots/bots API pakcage](https://pypi.python.org/pypi/zulip-bots)
* [zulip Flask bot server package](https://pypi.python.org/pypi/zulip-botserver)
I tested all three on my system and everything seems fine for now. The `zulip_bots` package doesn't ship fixtures or tests (like it shouldn't). I would really appreciate it if someone could test all three out in a virtualenv and give me some feedback! Thanks! :simple_smile:
=> python-zulip-api: Upgrade package versions (0.3.1 -> 0.3.2).

zulip_botserver/zulip_botserver/server.py
`json.loads()` expects unicode text in python 3, but request.data is a raw bytestring, so this failed for python 3. Switching to flasks `get_json` method, with `force=True` so that the MIME type gets ignored and the behavior is the same as before.
=> flaskserver: Load json python 3 compatible.

zulip_bots/zulip_bots/bots/yoda/test_yoda.py
The help message string was modified in yoda.py file to correctly
instruct the user. But the help message string was not modified
accordingly in the test file.
=> bots: Fix "help" message async in yoda.py and test_yoda.py.

.travis.yml
Fixes #44.
When running Travis on this in my fork, there weren't any errors, and the build for all 4 python versions went reasonably fast (~90 seconds per version): https://travis-ci.org/derAnfaenger/python-zulip-api/builds/265157077
=> travis: Test against Python 3.4, 3.5, and 3.6.

zulip_bots/zulip_bots/lib.py
get_bot_logo_path now first formats the path string with the name
of the bot before checking if the path exists. Not doing so is a
bug and causes the function to always return None.
Oops, my bad!
=> zulip_bots: Format string before checking if logo file exists.

.travis.yml, tools/server_lib/README.md, tools/travis_tests
This moves the `tools/lint` command to a new Travis job. 
I tested this on my repo, both with a [build where the linter should fail](https://travis-ci.org/derAnfaenger/python-zulip-api/builds/265557352), and a [build where it should pass](https://travis-ci.org/derAnfaenger/python-zulip-api/builds/265557955): 
A second commit fixes a small issue the litner complains about.
=> travis: Move linter to a separate job.

README.md
Note the difference between this README.md and the zulip repo's one: Here, the coverage status badge is directly obtained from codecov, whereas in zulip, it's fetched from img.shields.io. This is why this badge says "codecov", whereas zulip's badge says "coverage".
=> testing: Add build and coverage badges to README.md

zulip/integrations/log2zulip/log2zulip
I'm not thrilled with the `replace` error handler losing information
if the logfile contains invalid UTF-8 for some reason; but that sure
beats a UnicodeDecodeError, and for this script I can't quite be
bothered to run the rather tricky riddle trail that Python 3 makes it
to pass arbitrary byte data through layers of ordinary text processing.
=> log2zulip: Fix to work on Python 3.

.travis.yml
Before this commit, codecov got installed for each test job,
but was only needed *after* all jobs had passed: in after_success.
This lead to codecov silently failing, as it was not installed when
it was actually needed.
=> travis: Install codecodv in the correct place.

zulip/setup.py
The slash caused pip install ./zulip to fail on Windows with
Python 3.5.
This is the complete traceback:
```
Running setup.py install for zulip: started
Running setup.py install for zulip: finished with status 'error'
Complete output from command c:\users\robert\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Robert\\AppData\\Local\\Temp\\pip-roerrrzu-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Robert\AppData\Local\Temp\pip-q33jxzeb-record\install-record.txt --single-version-externally-managed --compile:
running install_data
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```
=> zulip setup.py: Remove redundant directory forward slash.

zulip/zulip/__init__.py
It is not guaranteed that the integration scripts in
the Zulip repository even specify a `provision` option.
Therefore, checking the value of this option would fail.
Updating this with getattr and a default value.
Fascinating how the added test suite immediately catches a bug.
=> zulip package: Make check for provision failsafe.

.codecov.yml
The previous threshold was taken over from the zulip repo,
which contains much more LOC. The new threshold reflects the
size of the `python-zulip-api` repo.
I made my calculations by running the command `git ls-files | grep -v .png | xargs cat | wc -l` on both repos, printing out the LOC.
Then, new_threshold = (zulip_LOC / python-zulip-api_LOC) * 0.03 ~= 0.85
zulip_LOC: 508196
python-zulip-api_LOC: 17905
I don't know if we have public figures similar to these, but I guess it'd be some impressive stats to mention (also for other repos).
=> codecov: Adjust failure threshold.

tools/run-mypy
This removes the excessively verbose lists of files
to be tested, and flushes the output after every print
to update the user on the current status in real time.
=> tools: Enhance output of run-mypy.

zulip_bots/zulip_bots/lib.py
The Zulip server, starting in 1.7, no longer sends
`is_mentioned` in the message payload, and it was buggy in
earlier versions, so now we check `flags`.
=> Look for `mentioned` in `flags`.

tools/run-mypy, zulip/integrations/git/zulip_git_config.py, zulip/integrations/irc/irc_mirror_backend.py, zulip/integrations/log2zulip/log2zulip, zulip/integrations/perforce/zulip_perforce_config.py, zulip/integrations/svn/zulip_svn_config.py, zulip/integrations/zephyr/process_ccache, zulip/tests/__init__.py, zulip/tests/test_default_arguments.py, zulip_bots/generate_manifest.py, zulip_bots/setup.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/provision.py, zulip_bots/zulip_bots/run.py, zulip_bots/zulip_bots/test_lib.py, zulip_bots/zulip_bots/test_run.py, zulip_bots/zulip_bots/zulip_bot_output.py, zulip_botserver/setup.py, zulip_botserver/tests/__init__.py, zulip_botserver/zulip_botserver/server.py
Finally, I have a PR ready :) Things to keep in mind while reviewing:
1. I annotated strings as `Text` in files that didn't have any annotations, and as `str` in files that already had `str` annotations.
2. I made a couple of minor changes to the code in places where I thought it made sense. I tested these changes, but it would be great to have someone look over.
3. I tried to minimize using `type: ignore`, but you'll still see it in a couple of places. Please let me know if you can suggest a way to avoid that.
Fixes #127.
=> mypy: Fix erroring files.

zulip_bots/zulip_bots/bots/github_detail/github_detail.conf, zulip_bots/zulip_bots/bots/weather/weather.conf, zulip_bots/zulip_bots/bots/weather/weather.py, zulip_bots/zulip_bots/lib.py
In the end, I decided against removing the section name. While it is redundant, ConfigParser works only with sections and makes config parsing very convenient. This makes the change for the external bots to comply with embedded bots really straightforward.
=>  zulip_bots: Enforce default config file schema.

zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/test_run.py
This fixes quirks related to the regex not covering all potential
weird usernames and adds tests for stripping the @-mentions.
=> zulip_bots: Fix and simplify extract_query_without_mention.

zulip/integrations/google/google-calendar, zulip/integrations/jabber/jabber_mirror_backend.py, zulip/zulip/__init__.py, zulip_bots/generate_manifest.py, zulip_bots/zulip_bots/lib.py, zulip_botserver/tests/test_server.py
=> mypy: Improve 'type: ignore' annotations.

tools/test-main
Before this patch, we were reading in old coverage data every
time we ran test-main and had a .coverage file lying around.
This would cause inaccurate data when you changed code, and it
would cause crashes if you moved your working directory on the
file system.
=> Ignore prior coverage data in tools/test-main.

zulip_bots/zulip_bots/lib.py
This patch is particularly useful in the scenario that your
API key is wrong or out of date, but it's targeted more
generally at any error that `client.get_profile()` reports.
=> Report client.get_profile() errors nicely (e.g. API key).

README.md
As mentioned in [this Zulip conversation](https://chat.zulip.org/#narrow/stream/GCI.20tasks/subject/Python.202.20or.203.20in.20python-zulip-api/near/347329), the docs don't mention whether or not to use Python 2 or 3, so I made a commit to make it more clear.
=> docs: Mention Python 3 in the README.

zulip_bots/zulip_bots/simple_lib.py, zulip_bots/zulip_bots/terminal.py
Make terminal.py exit gracefully with a message.
Modify output bot reply for better understanding for multi-line bot output. For example:
```
>python3 terminal.py --bot-config-file bots/weather/weather.conf weather 
Enter your message: New York
reply:
Weather in New York, US:
51.53 F / 10.85 C
Scattered Clouds
```
On providing no config file flag in simple_lib.py for a bot that uses conf, throws the following error:
`NameError: name 'sys' is not defined`
Corrected this.
=> bots: Clean up terminal.py for running bots directly.

.travis.yml, tools/provision
Python 2 venvs can now only be created with
tools/provision --force.
=> Make venv creation with Python 2 harder.

zulip_bots/zulip_bots/test_lib.py
As of now, only GET requests are supported by `mock_http_conversation`. However, this creates problems as some APIs utilize POST requests instead of GET ones. Therefore, create a system for using POST requests. (See https://goo.gl/p77qab for a discussion of this on the Zulip #integrations stream.)
To use a POST request with `mock_http_conversation`, specify
`"method": "POST"` in the `"request"` options of a fixture. For example,
"request": {
"api_url": "https://example.com/api",
"method": "POST",
"params": {
"foo": "bar",
"baz": "qwerty"
},
"json": {
"baz": "qwerty"
}
},
=> zulip_bots: Test POST requests in `mock_http_conversation`.

zulip_bots/setup.py, zulip_bots/zulip_bots/bots/link_shortener/doc.md, zulip_bots/zulip_bots/bots/link_shortener/fixtures/test_normal.json, zulip_bots/zulip_bots/bots/link_shortener/link_shortener.conf, zulip_bots/zulip_bots/bots/link_shortener/link_shortener.py, zulip_bots/zulip_bots/bots/link_shortener/test_link_shortener.py
Hello! Here is the Link Shortener Bot I created for the *Create your own URL shortener bot* Google Code-in task. I have tested it both manually and with the automatic `BotTestCase` class.
Before use and testing, the `key` property must be set to a goo.gl API key in `link_shortener.conf` and in the `mock_config_info` call in `test_link_shortener.py`.
In use, for example, you could write
> @**Link Shortener Bot** @**Joe Smith** See https://github.com/zulip/python-zulip-api/tree/master/zulip_bots/zulip_bots/bots for a list of all Zulip bots.
and LS Bot would respond
> https://github.com/zulip/python-zulip-api/tree/master/zulip_bots/zulip_bots/bots: https://goo.gl/NjLZZH
Please let me know if there is something I should improve or fix! Thank you!
=> zulip_bots: Create Link Shortener Bot.

zulip_bots/zulip_bots/run.py
See https://github.com/python/mypy/issues/1838.
=> zulip_bots: Make typing import work in Python 3.5.

zulip_bots/zulip_bots/bots/googletranslate/doc.md, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_403.json, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_conn_error.json, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_language_403.json, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_languages.json, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_normal.json, zulip_bots/zulip_bots/bots/googletranslate/fixtures/test_quotation.json, zulip_bots/zulip_bots/bots/googletranslate/googletranslate.conf, zulip_bots/zulip_bots/bots/googletranslate/googletranslate.py, zulip_bots/zulip_bots/bots/googletranslate/test_googletranslate.py
The Google translate bot translates messages using Google translate.
It uses the [google translate web API](https://cloud.google.com/translate/docs/reference/rest), so it requires a Google Cloud auth key to work. It used to use an unofficial python API, but the developer of that said that it could break at any moment, and I couldn't get any of the tests to work with it.
=> interactive bots: Create googletranslate bot.

zulip_bots/zulip_bots/bots/giphy/test_giphy.py, zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py, zulip_bots/zulip_bots/bots/googletranslate/test_googletranslate.py, zulip_bots/zulip_bots/bots/weather/test_weather.py, zulip_bots/zulip_bots/bots/yoda/test_yoda.py, zulip_bots/zulip_bots/bots/youtube/test_youtube.py, zulip_bots/zulip_bots/test_lib.py
This is an alternative testing-based (rather than default-behavior-based) approach to #58, which also could fix #55 - though again, via tests (test_lib.py), rather than lib.py.
This follows the idea I saw introduced with `test_bot_usage`. I ended up overriding the function in a few bots, though I had originally planned to keep it as local to test_lib.py as possible.
@showell You seem to be taking a lead on tests atm, so tagging you for review/comments.
=> Add automatic testing of responses to empty messages

tools/run-mypy
Accidentally missed it while writing the initial `force_include` logic.
=> [bitesize] tests: Add test_helloworld to run-mypy list.

zulip_bots/zulip_bots/bots/define/test_define.py, zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py, zulip_bots/zulip_bots/bots/wikipedia/wikipedia.py
This PR brings 100%  test coverage define bot.
Also when exploring the  wikipedia bot , I found that the bot replied with `null` in case of an error which is not  the very best response for the a normal user. So I made a change to return an error message incase of an error.
=> Improvements to wikpedia bot and tests for define bot

tools/run-mypy, zulip/integrations/jabber/jabber_mirror_backend.py, zulip/integrations/zephyr/zephyr_mirror_backend.py, zulip/zulip/__init__.py, zulip/zulip/examples/upload-file, zulip_bots/zulip_bots/bots/chess/chess.py, zulip_bots/zulip_bots/bots/incrementor/incrementor.py, zulip_bots/zulip_bots/bots/wikipedia/wikipedia.py, zulip_bots/zulip_bots/bots/xkcd/xkcd.py, zulip_bots/zulip_bots/bots/yoda/yoda.py
Also reset typing of ExternalBotHandler to Any after discussion.
This should also cause mypy to complain in future if `dict` or `list` are used, cf `Dict` and `List`.
**Update**: rebased to fix recent commits.
**Outstanding issue**: jabber_mirror_backend.py has a commented-out line, which appears to be inconsistent with the typing, in how it's currently used.
**Issue resolved**.
=> mypy: Add --disallow-any=generics & extend typing accordingly.

tools/run-mypy, zulip_bots/setup.py, zulip_bots/zulip_bots/bots/witai/doc.md, zulip_bots/zulip_bots/bots/witai/test_witai.py, zulip_bots/zulip_bots/bots/witai/witai.conf, zulip_bots/zulip_bots/bots/witai/witai.py
Wit.ai Bot communicates with the [Wit.ai API](https://wit.ai). It can be configured with any Wit.ai token and allows for setting up a custom `handler` function to handle Wit.ai responses. See [`doc.md`](https://github.com/zulip/python-zulip-api/compare/master...skunkmb:add-witai-bot?expand=1#diff-62073520e0ea4c4342bab168085bdb2b) for more details about setting up. Thanks!
(Done for the *Create your own wit.ai bot.* Google Code-in task.)
=> bots: Create Wit.ai Bot.

zulip_bots/zulip_bots/bots/dialogflow/dialogflow.py
These changes improve the dialogflow bot by:
- Instead of sending the actual error e.g. `error 204: error 500 internal server error.`, the bot will now send the message sent, if available, e.g. `could not get the weather.`
- Fixed mistake where if the dialogflow sent an empty message with no alternate response, it would raise a KeyError.
=> Update dialogflow bot to show user friendly messages

zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/lib_tests.py
Note that currently, the test for `run_message_handler_for_bot()` validates only one message. The framework is built though, and adding new test messages is straightforward.
=> Test run_message_handler_for_bot() and add a 'full_message' field for bots.

zulip_bots/setup.py, zulip_bots/zulip_bots/bots/jira/doc.md, zulip_bots/zulip_bots/bots/jira/jira.conf, zulip_bots/zulip_bots/bots/jira/jira.py, zulip_bots/zulip_bots/bots/jira/test_jira.py
*Jira Bot* can interact with the Jira API. It can **display**, **create**, or **edit** an issue. Before use, `username`, `password`, and `domain` must be set in `jira.conf`.
---
You could say,
> @**Jira Bot** get "BOTS-13"
and it would respond
> **Issue *BOTS-13*: Some Issue**
>
> - Type: *Task*
> - Description:
> > Some description.
> - Creator: *admin*
> - Project: *Bots*
> - Priority: *Medium*
> - Status: *To Do*
You could say
> @**Jira Bot** create issue "Some issue" in project "BOTS"' with type "Task" with description "This is a description" assigned to "skunkmb" with priority "Medium" labeled "issues, testing" due "2017-01-23"
and an issue would be created:
> Issue *BOTS-16* is up! https://example.atlassian.net/browse/BOTS-16
You could say
> @**Jira Bot** edit issue "BOTS-16" to use …
=> bots: Create Jira Bot.

zulip_bots/zulip_bots/bots/youtube/test_youtube.py, zulip_bots/zulip_bots/bots/youtube/youtube.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/test_lib.py
@showell can you review the approach I took here?
If you agree, I'll update the other bots currently using sys.exit(), and the ones using logging.error() where quit() should be used.
=> Add ExternalBotHandler.quit()

zulip_bots/zulip_bots/bots/giphy/doc.md, zulip_bots/zulip_bots/bots/xkcd/doc.md, zulip_bots/zulip_bots/bots/youtube/doc.md
Remove markdown includes from bot docs and inserted a link instead, cause markdown includes doesn't seem work(as shown in image).
=> Remove markdown includes {!running-bot.md!} from bot docs.

tools/run-mypy, zulip/integrations/hg/zulip-changegroup.py, zulip/integrations/jabber/jabber_mirror_backend.py, zulip/integrations/svn/post-commit, zulip/integrations/zephyr/check-mirroring, zulip/integrations/zephyr/zephyr_mirror_backend.py, zulip/zulip/__init__.py
Outstanding issues are within the api (zulip/zulip/__init__.py) and various integrations, totalling 21 errors locally. Pending review, all but the tools/run-mypy change should be mergeable now.
**Jan 8th 2018** Initial patches were merged in #251, so I rebased here and added commits which should resolve all outstanding mypy+strict-optional issues. The tools commit is now the last commit, but github does not show the correct order.
=> mypy: Include strict-optional by default when running tools/run-mypy

requirements.txt, zulip/setup.py, zulip_botserver/setup.py
The zulip and zulip_botserver packages specify mock as a runtime
dependency, which is only needed for testing during development.
So, it made more sense to move it to requirements.txt so that
it can be installed by ./tools/provision during development.
Fixes #293.
@roberthoenig FYI :)
=> requirements: Remove runtime dependency on mock.

zulip/zulip/__init__.py
Previously, remove_subscriptions called the
PATCH /api/v1/users/me/subscriptions endpoint, which is more like
an ad-hoc endpoint for bulk adding/removing subscriptions for the
user that makes the request. However, making a DELETE request
allows an admin to pass in the `principals` argument to unsubscribe
other users from streams as well, which is more consistent with how
add_subscriptions works.
@showell: FYI :)
=> zulip: Make a DELETE request in remove_subscriptions.

zulip/integrations/zephyr/zephyr_mirror_backend.py
I wrote a script to find duplicate imports, and this was the only one it could find.
=> zephyr_mirror_backend.py: Remove duplicate import.

zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py
The API has been updated it seems. The message for invalid api key is now includes ' (001)' in the end. This was causing the tests to fail.
=> bots: Fix test failure for Baremetrics bot.

zulip_bots/zulip_bots/bots/giphy/giphy.py, zulip_bots/zulip_bots/bots/giphy/test_giphy.py, zulip_bots/zulip_bots/custom_exceptions.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/lib_tests.py, zulip_bots/zulip_bots/test_lib.py
This method allows bots to validate their config info
in a standardized way. Adding the method to a bot is
optional, but recommended for bots with config options
that can be invalid, like api keys. The giphy bot serves
as an example.
The primary reason behind this is to allow the zulip
backend to validate config data for embedded bots. The
backend does not have a permanent bot class instance, so
validate_config() must be a static method.
=> bots: Add magic method validate_config().

zulip_bots/zulip_bots/bots/connect_four/controller.py, zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
This commit tests that we throw a BadMoveException if you
try to move into a "full" column in connect four.  This gets
the controller up to 100% coverage.
=> tests: Test handling of bad moves in connect four.

zulip_bots/zulip_bots/bots/merels/libraries/database.py, zulip_bots/zulip_bots/bots/merels/libraries/game.py, zulip_bots/zulip_bots/bots/merels/libraries/game_data.py, zulip_bots/zulip_bots/bots/merels/libraries/mechanics.py, zulip_bots/zulip_bots/bots/merels/merels.py, zulip_bots/zulip_bots/bots/merels/test_merels.py, zulip_bots/zulip_bots/game_handler.py
=> Port merels to game_handler.

.gitignore, tools/deploy
Sample session:
```
$ cd  ~/Documents/gitclones/python-zulip-api
$ source zulip-api-py3-venv/bin/activate
$ tools/deploy prepare c-four -p zulip_bots/zulip_bots/bots/connect_four -c ~/Documents/zulip/tworc -m connect_four.py -s $SERVER -k $KEY
pack: Created zip file at: .bots/c-four.zip.
upload: Uploaded the bot package to botfarm.
clean: Removed .bots/c-four.zip.
process: The bot has been processed by the botfarm.
$ tools/deploy prepare hello -p zulip_bots/zulip_bots/bots/helloworld -c ~/Documents/temp/zulip/onerc -m helloworld.py -s $SERVER -k $KEY
pack: Created zip file at: .bots/hello.zip.
upload: Uploaded the bot package to botfarm.
clean: Removed .bots/hello.zip.
process: The bot has been processed by the botfarm.
$ tools/deploy --server $SERVER --key $KEY stop test
stop: The bot …
```
=> [WIP] tools/deploy script for interfacing with the bot server.

zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py, zulip_bots/zulip_bots/game_handler.py
The cases I've seen & replaced the occurrence of user email with user avatar are:
* when a player wins,
* when a player quits the game, and
* when a player joins the game.
* telling a user about his turn
Please let me know if I've missed any case...
=> game_handler: Use avatars instead of emails in game handler messages.

tools/run-mypy
This assumes that files passed in force_include without any extension are meant to be run with mypy, and thus assumed to be python scripts.
Also, we ignore the most of the tools dir, except for the tools/deploy script for which #349 adds type annotations. Unless that PR is merged and rebased onto this, this one will fail the Travis build.
=> mypy: Support files without extensions for scripts in /tools.

zulip/zulip/__init__.py
Directly assigning session.headers overrides the default header
paramers and removes `{'Accept-Encoding': 'gzip, deflate'}` from
the headers.
=> API: Use `session.headers.update` method to add user-agent header.

zulip/zulip/__init__.py
Having a default parameter as '[]' may not be an issue with the current implementation, but general practice is to default to None and assign a default list subsequently.
=> zulip: Amend default value of remove_subscriptions:principals to None.

zulip/zulip/__init__.py
- Reduce use of Any, eg. in Callable parameters & narrow List;
- Use Optional where appropriate in more locations.
I'm not sure if the `narrow` type could be more general, but this is better than `Any` in any case.
=> mypy: Improve type annotations in Zulip API.

mypy.ini, tools/run-mypy, zulip/zulip/__init__.py, zulip_bots/zulip_bots/bots/idonethis/idonethis.py, zulip_bots/zulip_bots/bots/xkcd/xkcd.py, zulip_bots/zulip_bots/bots/yoda/test_yoda.py
There have been a few changes In the main Zulip repo, which feel reasonable to replicate here:
* migration to use a `mypy.ini` file, allowing finer-grained control of settings applying to different files;
* removal of the strict-optional setting - it's on by default (and can be controlled per-file in mypy.ini);
* addition of `warn_no_return` and `no_implicit_optional` settings for further strictness.
The latter setting requires some annotation changes and affects situations such as:
```python
def f(x: str=None) -> None:
...
```
These pass without this latter setting; now a more explicit `Optional[str]` is necessary, as might be expected.
The mypy.ini commit has a line which shows tracebacks on fatal error, and is included in the main repo; should we include it here?
=> Mypy.ini migration & simplification

zulip_bots/setup.py
The pip documentation recommends calling pip using a subprocess, instead of
importing it and using it's internal API. The API of pip==10.0.0 is different
from that of older versions, and provisioning is broken with this version.
https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program
Closes #370
=> tools: Call pip from a sub-process instead of importing it

tools/deploy
Add `tools/deploy ls` to show a overall status (name, status) of a user's bots. (according to #338)
Related to [PR in zulip-botmatrix](https://github.com/aero31aero/zulip-botmatrix/pull/6)
Examples of command output:
```
ls: There are the following bots on the botfarm:
NAME          STATUS
------------------------- ---------------
bot1:latest         running
```
```
ls: No bots found on the botfarm
```
=> #338 deploy: Add `tools/deploy ls` command.

tools/deploy
This simplifies the usage of the script by eliminating the need to
pass --server=$SERVER and --token=$TOKEN in each call to the script.
Also renames key=>token for consistency.
=> tools/deploy: Read $SERVER and $TOKEN environment variables.

zulip_bots/zulip_bots/run.py, zulip_bots/zulip_bots/test_run.py
=> #356 Automatically add a bot handler's parent dir to the python path 

zulip/setup.py
There were some issues running bots due to SSL issues.
Adding the extra_require requests[security] adds 3
additional packages that deal with these issues.
=> requirements: Add 'security' extra_require for requests.

zulip_bots/zulip_bots/terminal.py
This change was added to run.py in the commit 5992050d8276b523e099b76e55266912020342aa.
The same change is done to terminal.py so that the modules in the bot's directory can be imported when testing using `zulip-terminal` command.
=> zulip-terminal: Add bot's directory to sys.path.

zulip_botserver/tests/test.conf, zulip_botserver/tests/test_server.py, zulip_botserver/zulip_botserver/server.py
Previously, the botserver would accept any message sent
to it. This was a security hazard, since an attacker could
impersonate arbitrary users with arbitrary messages. We only
want the Zulip instance where a bot is registered to be able
to send out messages for that bot. To do this, this commits
adds a check for the security token associated with each
outgoing webhook bot. For each bot, its token is stored in
the botserverrc file. The server sends the token along with
each message.
=> botserver: Validate token before accepting message.

zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py, zulip_bots/zulip_bots/bots/wikipedia/wikipedia.py, zulip_bots/zulip_bots/bots/xkcd/test_xkcd.py, zulip_bots/zulip_bots/bots/xkcd/xkcd.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/simple_lib.py, zulip_bots/zulip_bots/test_lib.py
This PR is an update of #47.
Main changes:
* refactored against current master & changes since original PR;
* splitting/merging commits to more logical order;
* namedtuple -> class for BotIdentity, as quoted_name/mention is calculable;
* moved to `mention` from `quoted_name`, as former is simpler.
Feedback sought:
* Where should BotIdentity go? The current imports in `simple_lib.py` and `test_lib.py` seem off?;
* Should more bots be updated as part of this PR, or are two sufficient for examples?
=> Bots: Support run-time bot identity (update of #47)

zulip_bots/zulip_bots/bots/trivia_quiz/fixtures/test_new_question.json, zulip_bots/zulip_bots/bots/trivia_quiz/fixtures/test_status_code.json, zulip_bots/zulip_bots/bots/trivia_quiz/requirements.txt, zulip_bots/zulip_bots/bots/trivia_quiz/test_trivia_quiz.py, zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/test_lib.py, zulip_bots/zulip_bots/tests/test_lib.py
Things changed from the original PR:
* tests in commit 1
* tests in commit 2
* Fixed lint errors in commit 3 (diff:)
```
--- a/zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
+++ b/zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
@@ -38,7 +38,7 @@ class TriviaQuizHandler:
return
try:
quiz_payload = get_quiz_from_id(quiz_id)
-            except:
+            except KeyError:
bot_response = 'Invalid quiz id'
bot_handler.send_reply(message, bot_response)
return
@@ -132,10 +132,10 @@ def get_quiz_from_payload(payload):
def generate_quiz_id(storage) -> str:
try:
quiz_num = storage.get('quiz_id')
-    except:
+    except KeyError:
quiz_num = 0
quiz_num += 1
-    quiz_num = quiz_num % 1000
+    quiz_num = quiz_num % (1000)
```
I am confused about one thing:
Upon sending `''` or `help` …
=> bots: Add tests for trivia_quiz bot.

requirements.txt, tools/test-bots
This is a first step to explore how well pytest might work for the API repo in general; currently it only updates `test-bots`, though it is by far the more complex case of the test scripts.
In addition to using the test scripts explicitly, with pytest installed one can also run `pytest` or `pytest <path-to-tests>`, so `test-bots -p` is broadly equivalent to `pytest zulip_bots/zulip_bots/bots` except for some default settings. These default settings could be extracted into `pytest.ini` or similar files in an updated version of this commit or later. However, having the scripts too may remain useful if we adopt pytest.
The first commit uses test skipping to avoid testing the `BotTestCase` versions of the test functions; I've not found a way around this for pytest, but wanted a level playing …
=> [WIP] Enable pytest as test-runner in API repo (test-bots only so far)

zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py, zulip_bots/zulip_bots/bots/dialogflow/test_dialogflow.py, zulip_bots/zulip_bots/bots/dropbox_share/test_dropbox_share.py, zulip_bots/zulip_bots/bots/followup/test_followup.py, zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py, zulip_bots/zulip_bots/bots/game_of_fifteen/test_game_of_fifteen.py, zulip_bots/zulip_bots/bots/giphy/test_giphy.py, zulip_bots/zulip_bots/bots/github_detail/test_github_detail.py, zulip_bots/zulip_bots/bots/help/test_help.py, zulip_bots/zulip_bots/bots/idonethis/test_idonethis.py, zulip_bots/zulip_bots/bots/incrementor/test_incrementor.py, zulip_bots/zulip_bots/bots/merels/test_merels.py, zulip_bots/zulip_bots/bots/monkeytestit/test_monkeytestit.py, zulip_bots/zulip_bots/bots/salesforce/test_salesforce.py, zulip_bots/zulip_bots/bots/susi/test_susi.py, zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py, zulip_bots/zulip_bots/bots/twitpost/test_twitpost.py, zulip_bots/zulip_bots/bots/witai/test_witai.py, zulip_bots/zulip_bots/bots/xkcd/test_xkcd.py, zulip_bots/zulip_bots/bots/youtube/test_youtube.py
* Improve typing in a few cases
* Remove quite a few unnecessary imports
* Use consistent imports within test files and across bots; the latter isn't vital, but the code is simpler
* Resolve the issue with `monkeytestit` not being tested since it fails for python 3.4
* Name the merels test better and improve it's style (though it is not currently being run)
=> Bot tests: Various tidying & minor improvements

zulip/zulip/__init__.py, zulip/zulip/examples/edit-stream
About the quoting in the example, apparently the endpoint requires the strings to be quoted to be considered "valid JSON".
=> api: Implement PATCH /streams/<stream_id>.

.gitignore, tools/server_lib/test_handler.py, tools/test-bots, tools/test-botserver, tools/test-lib, tools/test-main, tools/test-zulip
This is a follow-up to #420, which completes the migration started there and tidies up the tests slightly.
Each test script run from `test-main`, and that script too, now support passing in `-p` to run via pytest, and also with `-v` to show each test.
I'm unsure if we'd like to see `-v` mode as the default; its output is similar to that from `unittest`, but can be verbose if the tests pass :)
`test-lib` is simplified a lot by using the common `test_handler` as in the other tests, with an amendment to that function, also comprising a header to nicely divide the test output.
If this all looks good, the pytest options can be factored out into a configuration file, but they're only in two locations right now.
=> Tests: Simplify & enable use of pytest to run all tests

zulip_bots/zulip_bots/bots/file_uploader/doc.md, zulip_bots/zulip_bots/bots/file_uploader/file_uploader.py, zulip_bots/zulip_bots/bots/file_uploader/test_file_uploader.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/simple_lib.py, zulip_bots/zulip_bots/test_lib.py, zulip_bots/zulip_bots/tests/test_lib.py
Fixes #351.
Added methods ExternalBotHandler.upload_file() and ExternalBotHandler.upload_file_from_path() to upload local files to Zulip server. I decided to allow user to upload any file located on his machine, not only inside bot's local directory. 
P.S. Also I added commit c7acf50 with `file_uploader` bot as an example of using new methods for uploading files. If it is unnecessary I will revert this commit.
=> #351 Add file upload access to the bot API

zulip/zulip/__init__.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/tests/test_lib.py
I tried running `connect_four` game and it failed with these errors:
```
Traceback (most recent call last):
File "/home/klitzy/python-zulip-api/zulip-api-py3-venv/bin/zulip-run-bot", line 11, in <module>
load_entry_point('zulip-bots', 'console_scripts', 'zulip-run-bot')()
File "/home/klitzy/python-zulip-api/zulip_bots/zulip_bots/run.py", line 123, in main
bot_name=bot_name
File "/home/klitzy/python-zulip-api/zulip_bots/zulip_bots/lib.py", line 300, in run_message_handler_for_bot
message_handler = prepare_message_handler(bot_name, restricted_client, lib_module)
File "/home/klitzy/python-zulip-api/zulip_bots/zulip_bots/lib.py", line 263, in prepare_message_handler
message_handler.initialize(bot_handler=bot_handler)
File "/home/klitzy/python-zulip-api/zulip_bots/zulip_bots/game_handler.py", …
```
=> zulip_bots: Fix get_storage request arguments in StateHandler.

zulip_bots/zulip_bots/finder.py, zulip_bots/zulip_bots/run.py, zulip_bots/zulip_bots/tests/test_run.py
Fixes #357.
Change logic to run bot by `zulip-run-bot` to the following:
- If `zulip-run-bot` was run with _name_ as path to bot's file, then import bot from file and add bot's parent dir to `sys.path`;
- If `zulip-run-bot` was run with some _name_ (not pointing to file) then:
- try to import bot from file located at `zulip_bots/zulip_bots/bots/{name}/{name}.py`. If import was completed succesfully, then add add bot's parent dir (`zulip_bots/zulip_bots/bots/{name}`) to `sys.path`;
- try to import bot by specified module _name_. If import was completed successfully, then also check that `args.provision` was *not* passed
=> #357 Add a better way to run standalone bots 

zulip/zulip/__init__.py
**Testing plan**: lint and mypy checks passed locally, tried the example in the function's comment.
=> api: Implement POST /users/me/subscriptions/properties.

zulip_bots/zulip_bots/bots/jira/fixtures/test_create.json, zulip_bots/zulip_bots/bots/jira/fixtures/test_create_error.json, zulip_bots/zulip_bots/bots/jira/fixtures/test_edit.json, zulip_bots/zulip_bots/bots/jira/fixtures/test_edit_error.json, zulip_bots/zulip_bots/bots/jira/jira.py
JSON post requests aren't supposed to be form-encoded (see http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests)
=> Fix post requests for JIRA bot

zulip_botserver/tests/test_server.py
This wraps up the leftover testing work from #452.
=> botserver: Add tests for reading config section by bot name.

zulip/zulip/__init__.py
**Testing plan:** lint and mypy checks passed locally. Tested the example in Python's REPL interpreter.
=> api: Implement GET /server_settings.

zulip/zulip/__init__.py, zulip/zulip/examples/get-user-presence
Given that this method fetches the presence status for a single user, the "get_presence" name should be reserved for the endpoint that gets the presence for all users.
=> api: Rename "get_presence" to "get_user_presence".

tools/provision
Previous tuple generation logic was throwing an error parsing version like 3.6.7rc1
because micro-versions like '7rc1' cannot be converted into integer.
Fix #482
=> provision: Refactor version tuple generation logic.

tools/test-bots, zulip_bots/zulip_bots/bots/chessbot/requirements.txt
This PR specifies a version for Chessbot so that it will continue to function properly if the library is updated. This also updates `test-bots` to remove a temporary fix for Chessbot.
=> bots: Fix a Chessbot dependency error.

zulip/integrations/bridge_with_irc/irc-mirror.py, zulip/integrations/bridge_with_irc/irc_mirror_backend.py
This fixes #106.
Can be tested with 
```
./irc-mirror.py --irc-server=irc.freenode.net --channel='#python-mypy' \
--nick-prefix='irc_mirror' \
--site="https://chat.zulip.org" --stream='test here' --topic='IRC' \
--user=<bot-email> --api-key=<bot-api-key>
```
Note the `--stream` arg is added here.
=> Fix bridge_with_irc

zulip/integrations/bridge_with_irc/README.md
This problem (bots not being subscribed) has happened way too often.
=> bridge_with_irc: Tell people to subscribe their bots to the stream.

zulip/zulip/examples/get-history
This PR adds a script that can download the history of a stream or a topic from Zulip.
```
$ ./get-history --help
usage:
Gets the complete history of a particular stream or a particular topic in Zulip
and store them in JSON format.
get-history --stream <stream_name> [--topic <topic_name> --filename <file_to_store_messages>]
Example: get-history --stream announce --topic important
optional arguments:
-h, --help            show this help message and exit
--stream STREAM       The stream name to get the history
--topic TOPIC         The topic name to get the history
--filename FILENAME   The file name to store the fetched history. Default
'history.json'
```
Written JSON file format :
```json
[
{
"content": "I am interested in working on #P476.\n\nIf I understand it correctly, the script …
```
=> zulip/examples: Add a script to get complete history of a narrow.

zulip/zulip/__init__.py
Context: I'm in the process of migrating ZT to use 'full' API calls, rather than `do_api_query` or `call_endpoint`, which were necessary to call endpoints directly when the python API didn't have the functionality.
I wondered why the `add_reaction` method wasn't working; apparently the method doesn't pass the actual data to `call_endpoint`, so it's not really so surprising!
I also corrected the example usage text, which had an extra `emoji` in the method name.
=> API: Fix add_reaction method to pass reaction_data.

zulip/zulip/__init__.py
This replaces one case where the base ZulipError was raised, and another
where the original exception was re-raised.
This method, and so all API calls, should now only fail via raising this
Exception or by a non-'success' result in the return value dict; this
should avoid leaking any implementation detail and clarify expectations
in user code.
=> api: Add NetworkError Exception & use twice in do_api_query.

zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py
The tictactoe bot requires clean up and coverage improvements due to low
maintenance. Coverage for tictactoe.py was very low due to several functions
entirely missed in line coverage. Increased line coverage from 41.66%
to 50%. Testing was done locally by running ./tools/test-main until we
received response 'ok', as well as using coverage to give us the final
coverage percentage.
#417
=> bot tests: Extend tests for TicTacToeModel.

zulip/setup.py
Apparently we still support Python 2.7 for some reason.
Follow-up to #521.
=> Restore dependency on typing package for Python < 3.5

zulip/integrations/rss/rss-bot
I believe that rss-bot is pointing to wrong page on documentation, this MR should fix it.
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>
=> rss-bot: Updated link pointing to .zuliprc

requirements.txt, zulip/zulip/__init__.py
Python 3.8 removes `platform.linux_distribution` and `distro` is the
recommended replacement to use for this function.
=> zulip: Use distro.linux_distribution instead of platform

requirements.txt, zulip/setup.py
The just-released API package has a significant issue, which doesn't install the `distro` package as a dependency of the `zulip` package directly.
This small (but important) PR should fix that.
@eeshangarg @timabbott
=> zulip: Move dependency on distro into zulip package.

zulip/integrations/twitter/twitter-bot
Twitter supports phrase search by quoting terms such as "Zulip API".
If we use the feature, the current twitter-bot can't detect used
search phrase. We can detect used search phrase with this change.
=> twitter: Add support for phrase.

zulip/integrations/bridge_with_irc/irc_mirror_backend.py
If no error occurred then bridge_with_irc shows no output on the terminal and users don't know if they are connected to the irc server or not. Add an output line after connection so that a message appears if connection to irc server has been successful.
=> bridge_with_irc: Print message on successful connection.

tools/provision
Basically replaces "the" with "to"
=> Fix a typo in virtualenv instruction

zulip/integrations/bridge_with_irc/irc_mirror_backend.py
Edit error and success messages of zulip-irc bridge to be more
user friendly. Also check whether zulip bot is subscribed before
starting irc bot.
=> bridge_with_irc: Make bridge more user-friendly.

zulip/integrations/bridge_between_zulips/run-interrealm-bridge, zulip/integrations/bridge_with_matrix/matrix_bridge.py
For the reason why, see https://chat.zulip.org/#narrow/stream/127-integrations/topic/bridge.20between.20zulips.
=> bridges: Remove sender field from message data.

zulip/zulip/__init__.py
This refactors get_user_by_id to take arguments like
`include_custom_profile_fields = True` instead of
{include_custom_profile_fields: True}.
=> api: Refactor get_user_by_id to take keyword arguments

zulip/zulip/__init__.py
This implements DELETE /users/{user_id} api endpoint.
=> api: Implement DELETE /users/{user_id} api endpoint

zulip_bots/zulip_bots/finder.py
`ModuleNotFoundError` is a subclass of `ImportError`, which is handled on the previous line; furthermore, it doesn’t exist in Python 3.5.
=> finder: Remove ModuleNotFoundError handler

tools/.coveragerc, zulip/README.md, zulip/setup.py, zulip_bots/setup.py, zulip_botserver/setup.py
Even though the this repo is now python3.5+, we have retained a `six` and `typing` dependency, which we can now remove.
Also, the URL for each package currently points to zulip.org -> zulipchat.com. The second commit should add links in the PyPI sidebar to the git repo and the zulipchat.com/api page, which otherwise are not particularly obvious.
=> Remove six/typing dependencies & add project_urls

zulip_bots/zulip_bots/bots/helloworld/helloworld.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/simple_lib.py, zulip_bots/zulip_bots/test_lib.py, zulip_bots/zulip_bots/tests/test_lib.py
This adds a react() function that allows a bot to react to a message with an example and tests.
=> ExternalBotHandler: Support adding reactions to message for a bot..

zulip/integrations/zephyr/zephyr_mirror_backend.py, zulip/zulip/__init__.py
This reduces the number of retries that might spam APIs.
There is some complexity here which is left un-managed -- for
instance, maybe_restart_mirroring_script does a number of restart
attempts, and then fails, but will be retried every 15s by the
surrounding `process_loop`.  Previously, it would merely have looped
forever inside maybe_restart_mirroring_script.
Three loops are intentionally left as infinite `while True` loops,
that merely cap their backoff at the default 90s.  Their callers do
not expect, or have any way to handle more gracefully, a failure of
the expected-infinite-loop in `process_loop` or `zulip_to_zephyr`.
They maintain their previous behavior of retrying forever, albeit more
slowly.
=> zephyr: Use exponential backoffs in retry loops.

zulip/zulip/__init__.py
This updates the type annotation for the 'principals' argument
to accept list of email addresses as well as user ids.
=> api: Update type annotation in 'remove_subscriptions'.

zulip/integrations/bridge_with_slack/README.md, zulip/integrations/bridge_with_slack/bridge_with_slack_config.py, zulip/integrations/bridge_with_slack/requirements.txt, zulip/integrations/bridge_with_slack/run-slack-bridge
It works when run on a server where websocket connections aren't blocked. `check_zulip_message_validity` is copied from bridge_with_matrix, so I think there should be a util library to import all common bridge operations.
=> bridge: Initialize bridge_with_slack.

zulip/tests/test_hash_util_decode.py, zulip/zulip/__init__.py
This adds `hash_util_decode()` to decode a `hash_util_encode()` [present in [zulip/zulip's zerver/lib/url_encoding.py](https://github.com/zulip/zulip/blob/master/zerver/lib/url_encoding.py)] encoded string.
The intent is to facilitate code sharing among various python clients (primarily, Zulip Terminal).
The string replacement before the `unquote` is to recoup for the custom string replacements in [zulip/zulip's zerver/lib/url_encoding.py](https://github.com/zulip/zulip/blob/master/zerver/lib/url_encoding.py).
Conversation link: https://chat.zulip.org/#narrow/stream/127-integrations/topic/Decode.20server.20URLs/near/977374
=> zulip: Add hash_util_decode() to decode server encoded URL excerpts

tools/provision
Currently, the provision script gives us something like this on Windows:
```bash
Run the following to enter into the virtualenv:
source C:\Users\qedk\python-zulip-api\zulip-api-py3-venv\Scripts\activate
```
However, `bash` does not work with  backslashes and will give us an error saying `No such file or directory`.
This commit addresses that so we get the correct command with the forward slashes:
```bash
Run the following to enter into the virtualenv:
source C:/Users/qedk/python-zulip-api/zulip-api-py3-venv/Scripts/activate
```
=> provision: Fix source command on Windows

zulip/integrations/jabber/jabber_mirror_backend.py
The server no longer sends occupy/vacate events
for streams.
The mirror should continue to work fine by processing
subsription-related events.
=> jabber mirror: Remove code for occupy/vacate events.

zulip/integrations/rss/rss-bot
- Add init method
- Change return hashlib.md5 synthax
Signed-off-by: Manu LN <manu+github@lacavernedemanu.fr>
Before changes, while trying to get rss infos in RSS stream the script output was 
```
Traceback (most recent call last):
File ".local/share/zulip/integrations/rss/rss-bot", line 190, in <module>
entry_hash = compute_entry_hash(entry)  # type: str
File ".local/share/zulip/integrations/rss/rss-bot", line 131, in compute_entry_hash
return hashlib.md5(entry_id + str(entry_time)).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
=> Changes to make rss bot working with zulip 3.3 and Debian 10.7 :

zulip/zulip/__init__.py
Update `reaction_data` type in add_reaction and
remove_reaction, from Dict[str, str] to Dict[str, Any]
=> zulip/zulip/__init__.py: Update `reaction_data` type.

requirements.txt, tools/lint, zulip_bots/zulip_bots/bots/file_uploader/test_file_uploader.py, zulip_bots/zulip_bots/bots/yoda/yoda.py, zulip_bots/zulip_bots/finder.py, zulip_bots/zulip_bots/run.py, zulip_bots/zulip_bots/tests/test_finder.py, zulip_bots/zulip_bots/tests/test_run.py, zulip_botserver/tests/test_server.py
Tests were failing on Windows since paths are case-insensitive on it.
This uses pathlib library to compare paths on all platforms.
Fixes #651
=> Fix tests failing on Windows.

zulip/integrations/bridge_with_irc/irc_mirror_backend.py, zulip/integrations/jabber/jabber_mirror_backend.py, zulip/zulip/__init__.py, zulip/zulip/examples/get-subscriptions
I replaced every occurrences of list_subscriptions and list-subscriptions except for https://github.com/zulip/python-zulip-api/blob/5b5fda2354f4488693f0f00def68eb8a9b426e67/zulip_bots/zulip_bots/bots/baremetrics/test_baremetrics.py#L68-L75 and list-subscriptions in baremetrics.
=> API: Rename list_subscriptions to get_subscriptions.

zulip_bots/zulip_bots/bots/incrementor/incrementor.py, zulip_bots/zulip_bots/bots/incrementor/test_incrementor.py
#673 
This allows the incrementor to regard the error message from the server (such as having the edit time limit expired). It also adds a test for this feature. 
If the API returns an error message when the incrementor attempts to update a message, the incrementor will send a new message instead.
=> zulip-bots: Fix incrementor to handle edit time limit error.

zulip/zulip/__init__.py
In zulip/zulip@3947b0c80a26b9126540ada996f027aac03063b7, we replaced
the legacy endpoint to use the term "linkifier" instead of
"filter" and to return the data in a dictionary format.
None of the official clients currently actually use this
endpoint.
=> zulip: Replace GET realm/filters with realm/linkifiers.

zulip_botserver/zulip_botserver/server.py
In zulip/zulip@b998138d3ab8ca0ea212c00469042349f8c3fe53, we introduce a check for responses from outgoing webhooks that require them to be a dictionary. This fixes the return value of the botserver view function to accommodate with the change from the serverside.
=> botserver: Return a valid JSON that is acceptable to outgoing webhooks.

zulip_botserver/zulip_botserver/server.py
Value of type "Optional[Any]" is not indexable error was originated by mypy.
```
zulip_botserver/zulip_botserver/server.py:172: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:179: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:180: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:183: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:187: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:188: error: Value of type "Optional[Any]" is not indexable
zulip_botserver/zulip_botserver/server.py:189: error: Value of type "Optional[Any]" is not indexable
```
and …
=> botserver: Fix mypy error.

zulip_bots/zulip_bots/bots/incrementor/incrementor.py, zulip_bots/zulip_bots/lib.py
The context manager is implemented based on a newly added storage calledCachedStorage. It is buffered storage that doesn't sync with the database until it's flushed. With CachedStorage, we can implement the context manager easily by loading all the data on __enter__ and just flush all the modified (dirty) data on __exit__. This approach can help the user minimize the number of round-trips to the server almost invisibly (despite the fact that they need to use it with "with").
https://zulip.com/api/writing-bots#bot_handlerstorage
Manually tested with the incrementor bot.
Possible upcoming work: adding documentation and tests
#679
=> Implement context manager for bot storage

zulip_bots/zulip_bots/lib.py
Fixes the bug that the context manager doesn't actually return the cache storage due to a typo.
=> zulip-bots: Yield cache storage instead bot storage.

zulip/integrations/bridge_with_matrix/test_matrix.py
Fixes a188a4e72a525847ded80eee6e864e43715e3bd7.
=> matrix: Fix test failure brought by the hint for usernames change.

zulip/integrations/git/post-receive
Without `universal_newlines=True` or `text=True`, `subprocess.check_output` returns `bytes`, not `str`, so it makes no sense to compare its return to `"true"`. But upstream Git’s behavior only depends on the filename, not whether the repository is bare; emulate this more closely.
=> git: Fix git_repository_name

zulip/integrations/zephyr/zephyr_mirror_backend.py
Found by trying to enable mypy `strict_equality`. @timabbott FYI.
=> zephyr_mirror_backend: Add missing parens for calling lower()

zulip/integrations/bridge_with_slack/requirements.txt
It is required by the Slack library, but strangely not installed. So we
explicitly specify it.
=> Slack bridge: Explicitly require aiohttp.

zulip_bots/setup.py
This change is intended to reduce confusion between zulip-bot-shell
(test bots interactively without a server) and the zulip/zulip-terminal
project and its associated command (zulip-term).
Latest reference at https://chat.zulip.org/#narrow/stream/127-integrations/topic/Migrating.20bot.20zulip-terminal.20script
Docs change in main repo at zulip/zulip#20310
=> bots: Migrate script name from zulip-terminal to zulip-bot-shell.

tools/provision
The version of pip that comes bundled with venv is often outdated, which can lead to unexpected errors when installing dependencies. This commit ensures that pip is upgraded to the latest version before any dependencies are installed.
This commit fixes an issue I discovered in my WSL2 development environment. Before this commit, running `python3 tools/provision` resulted in the following exception:
``` 
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine->-r /home/eeshangarg/python-zulip-api/requirements.txt (line 2))
Cache entry deserialization failed, entry ignored
Using cached https://files.pythonhosted.org/packages/f9/4b/1cf8e281f7ae4046a59e5e39dd7471d46db9f61bb564fddbff9084c4334f/cryptography-36.0.1.tar.gz
Complete output from command …
```
=> tools/provision: Bump required pip version from >=9.0 to >=10.

zulip/zulip/__init__.py
The documented API for `DELETE /api/v1/users/me/subscriptions` is that `principals` should be omitted to remove a subscription for the calling user.  A call with `principals=[]` should have a different meaning, but a server bug currently conflates this with a call omitting `principals`. Avoid relying on this bug.
=> zulip: Fix principals default for remove_subscriptions

zulip/setup.py, zulip/zulip/__init__.py
See https://chat.zulip.org/#narrow/stream/378-api-design/topic/python.20bindings.20and.20constants
The first commit is useful as it integrates with the API directly; the second doesn't integrate with the API as the method parameter data types are unspecified dicts right now (see discussion).
=> api: Add subset of Literal types used in zulip-terminal

zulip/zulip/__init__.py
There are cases where the call to get_server_settings returns a JSON response with a connection error. In the case of such an unsuccessful response, we should raise an appropriate exception instead of parsing the response as though it was successful.
@timabbott Could you please take a look at this? Not sure if this is the right fix. Also, wondering if I should put a test for this somewhere in `zulip_botserver`?
=> zulip: Reraise exceptions in do_api_query. 

zulip/integrations/bridge_with_matrix/requirements.txt
=> bridge_with_matrix: Bump matrix-client 0.2.0 -> 0.4.0.

zulip/integrations/bridge_with_matrix/matrix_bridge.py
This problem has happened far too frequently. See e.g. https://chat.zulip.org/#narrow/stream/9-issues/topic/.E2.9C.94.20Matrix.20Zulip.20integration.20error/near/1388040.
=> Matrix bridge: Print reminder to subscribe the bots on startup.

requirements.txt, zulip/integrations/bridge_with_matrix/README.md, zulip/integrations/bridge_with_matrix/matrix_bridge.conf, zulip/integrations/bridge_with_matrix/matrix_bridge.py, zulip/integrations/bridge_with_matrix/requirements.txt, zulip/integrations/bridge_with_matrix/test_matrix.py, zulip/integrations/bridge_with_matrix/todo.md, zulip/setup.py
Hi :)
As discussed [here](https://chat.zulip.org/#narrow/stream/127-integrations/topic/Matrix.20.3C-.3E.20Zulip.20Bridge), I'm now creating the pull request for the new Matrix <-> Zulip bridge.
See [here](https://chat.zulip.org/#narrow/stream/127-integrations/topic/Use.20upload_file.20with.20in-memory.20IO-object) for further discussions about uploading an in-memory file-object to a Zulip server.
Feedback would be greatly appreciated! :)
=> [WIP] Enhanced matrix bridge.

requirements.txt, zulip/integrations/bridge_with_matrix/README.md, zulip/integrations/bridge_with_matrix/matrix_bridge.conf, zulip/integrations/bridge_with_matrix/matrix_bridge.py, zulip/integrations/bridge_with_matrix/requirements.txt, zulip/integrations/bridge_with_matrix/test_matrix.py, zulip/integrations/bridge_with_matrix/todo.md, zulip/setup.py
Hi :) This PR aims to fix #723 for Windows.
As discussed there, python-magic seems to be problematic on Windows. However, I noticed in the output of the CI that `python-magic-bin` doesn't get installed as requested. (It's needed to provide the Windows library support as described [here](https://pypi.org/project/python-magic/)). Thus, my first attempt to fix the Windows support is trying to get `python-magic-bin` properly installed. If this doesn't work, I disable the magic-support in Windows completely.
=> integrations: Enhanced matrix bridge. (Fix #723)

pyproject.toml, zulip/integrations/zephyr/check-mirroring, zulip/integrations/zephyr/process_ccache, zulip/integrations/zephyr/zephyr_ctypes.py, zulip/integrations/zephyr/zephyr_mirror_backend.py
Our custom patched version of python-zephyr only worked on Python 2. Now we don’t need python-zephyr at all.
Tested `zephyr_mirror.py` with personals in both directions on an Athena dialup.
=> zephyr: Fix thread safety; remove python-zephyr in favor of ctypes

requirements.txt, zulip/integrations/git/zulip_git_config.py, zulip/integrations/openshift/zulip_openshift_config.py, zulip/integrations/perforce/zulip_perforce_config.py, zulip/integrations/svn/zulip_svn_config.py, zulip/integrations/zephyr/check-mirroring, zulip/integrations/zephyr/zephyr_mirror.py, zulip/integrations/zephyr/zephyr_mirror_backend.py, zulip/zulip/__init__.py, zulip_bots/zulip_bots/bots/define/test_define.py, zulip_bots/zulip_bots/bots/flock/flock.py, zulip_bots/zulip_bots/bots/game_of_fifteen/game_of_fifteen.py, zulip_bots/zulip_bots/bots/incident/incident.py, zulip_bots/zulip_bots/bots/merels/libraries/game.py, zulip_bots/zulip_bots/bots/stack_overflow/test_stack_overflow.py, zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py, zulip_bots/zulip_bots/bots/weather/test_weather.py, zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py, zulip_bots/zulip_bots/bots/youtube/youtube.py, zulip_bots/zulip_bots/lib.py, zulip_bots/zulip_bots/test_lib.py, zulip_bots/zulip_bots/tests/test_run.py
Newer pull requests are getting linter errors to reformat files due to updates in the upstream.
This reformats the affected files using black, and pin it in `requirements.txt`; fixes a mypy error for a missing return type annotation.
However, I think we need to look into options like Poetry to do dependencies versioning properly in future follow-ups.
=> Fix recent linter errors

zulip/integrations/rss/rss-bot
I've experienced that `rss-bot` works fine when using config file, but fails when `--site`, `--api-key`, and `--user` are provided via command line. The error is the following:
```
{'result': 'error', 'msg': 'Invalid mirrored message', 'code': 'BAD_REQUEST'}
```
Debugging shows that in the latter case `rss-bot` calls `zulip.Client.send_message()` with `"sender"` field in `message_data`. In the former case `"sender"` is `None`. Clearly, it is a bug that `rss-bot`'s behaviour depends on `--user` being provided on the command line.
`"sender"` field in request causes [this exception](https://github.com/zulip/zulip/blob/e26f9180c16f6be088209afbf3a05fd0c4767872/zerver/views/message_send.py#L227) on the server side.
Judging by surrounding code, `"sender"` is only expected together with a …
=> Remove unnecessary "sender" in request data

zulip/zulip/__init__.py
I tested this with https://github.com/showell/zulip-api-examples/blob/main/heartbeat_bug.py.
See https://chat.zulip.org/#narrow/stream/137-feedback/topic/api.20client.20silent.20failure for more context.
=> Do not send heartbeat events to clients.

zulip/integrations/rss/rss-bot
rss-bot selects the topic of its RSS notification messages based on the topic of the RSS feed. Monitoring a large number of RSS feeds therefore leads to a large number of topics in the stream. Also, the user has no option to customize the topic names.
This patch adds a new `--subject` argument that replaces the topic for all RSS feed notifications with the provided string. If no custom topic is provided, the bot uses the default behaviour described above.
=> rss-bot: Custom topic configuration

zulip/zulip/__init__.py
This adds support to adding linkifiers with the new URL template syntax.
This PR relies on https://github.com/zulip/zulip/pull/23125 to determine the feature level that changes the endpoint.
=> api: Update add_realm_filter to support url_template.

zulip_botserver/zulip_botserver/server.py
[CZO Discussion](https://chat.zulip.org/#narrow/stream/191-kandra-support/topic/outgoing.20webhook.20triggers.20rename/near/1644148)
The JSON payload that Zulip server POST for outgoing webhooks has [`trigger` as one of the fields](https://zulip.com/api/outgoing-webhooks#fields-documentation).
In https://github.com/zulip/zulip/commit/c4e4737, we renamed the `private_message` value to `direct_message`.
This commit adds support to the botserver for handling `direct_message` as a trigger value. It still supports
`private_message` for self-hosted server compatibility.
=> bot_server: Support trigger value `private_message` renamed to `direct_message`.

zulip_bots/zulip_bots/bots/merels/merels.py
I don’t entirely understand the purpose of having a separate `MerelsStorage` class that’s only ever used with the fixed string `"merels"` as `topic_name`, but this class variable sharing was clearly and observably wrong.
Cc @amanagr (#324).
=> merels: Convert incorrectly shared class variable to instance variable

zulip/integrations/bridge_with_irc/irc_mirror_backend.py
The proper solution would be to handle each errors differently. But for now, logging the message is at least informative to the user.
=> IRC: Handle error by displaying the error message.

zulip/integrations/bridge_with_slack/run-slack-bridge
This is based on https://github.com/zulip/zulip/commit/ff647dff03f178c329240c0e938d3fff8fbc5ab0, from #761.
=> bridge_with_slack: Do not use a stale Zulip client for send_message.

zulip/zulip/__init__.py
Python wrapper function for the new endpoint introduced in ZFL 226 to fetch a stream's email address. This could enhance the ease of making calls within zulip terminal and potentially other clients.
=> api: Add get_stream_email_address().

zulip/integrations/zephyr/zephyr_mirror_backend.py
Zulip will reject sending these, so there is no need to construct them.
=> zmirror: Drop empty zulip messages.

zulip/integrations/litellm/README.md, zulip/integrations/litellm/requirements.txt, zulip/integrations/litellm/summarize-topic
Copy pasted from https://github.com/zulip/zulip/pull/31897
For testing you need access token from https://huggingface.co/settings/tokens (or set the correct env variable with the access token if using a different model)
Then set `os.environ["HUGGINGFACE_API_KEY"] = "YOUR_API_KEY"` in `tools/summarize-topic`.
Just run `tools/summarize-topic` to generate same summary.
```bash
$ ./tools/summarize-topic --help
usage: summarize-topic [-h] [--url URL] [--model MODEL]
options:
-h, --help     show this help message and exit
--url URL      The URL to fetch content from
--model MODEL  The model name to use for summarization
```
NOTE: only topic links are supported right now.
=> summarize-topic: Add a tool to summarize topic.

zulip/integrations/rss/rss-bot
Fixes #836.
Mastodon feed entries do not have a 'title' field.
We could handle this
- by not displaying the title, or
- by displaying the description as the title (truncated to a constant value)
This PR implements the former approach.
<details open>
<summary> Screenshots </summary>
**No Title (former approach)**
**Truncated Description - 60 characters (latter approach)**
</details>
=> rss-bot: Handle feed entries that lack a `title` field.

.github/pull_request_template.md
Hopefully, this will help improve the quality of new-contirbutor pull requests to this project.
=> github: Add a zulip/zulip style pull request template.

zulip/integrations/litellm/summarize-topic
This avoid us from partially capturing channel name if it includes `-`.
=> summarize-topic: Use channel id instead of name.

zulip/integrations/bridge_with_slack/README.md, zulip/integrations/bridge_with_slack/bridge_with_slack_config.py, zulip/integrations/bridge_with_slack/run-slack-bridge
Currently, we use Slack's legacy RTM API as the "listener" for messages from Slack to Zulip. This PR updates our Slack Bridge to use the Webhook integration to send messages from Slack to Zulip.
We now utilize the Slack Webhook integration for this part of the bridge, which is being updated to use the latest Event API in [PR#30465](https://github.com/zulip/zulip/pull/30465). Here are the key changes in this PR :
- Updated the documentation on how to set up the updated Slack Bridge.
- Removed the RTM API-based connection. Users can still use an older version of this repo if they want to maintain their existing connection.
- Made the bridge compatible with the Slack Webhook integration by preventing looping messages.
_new Slack Bridge documentation:_
Fixes #825.
=> Slack bridge: Update Slack bridge with Events API.

zulip/integrations/git/doc.md
Moved from [#32780](https://github.com/zulip/zulip/pull/32780), following the migration of the integration docs of the API integrations.
1. Warning note: "This integration is meant to be executed on your Git server." -> "This integration adds a `post-receive` hook to your Git repository on your Git server."
2. Rewritten instruction: "Symlink the `post-receive` hook of your Git repository by running:" -> "If your Git server and your Zulip server are on the same machine, symlink the `post-receive` hook of your Git repository in your Git server by running: ...command... Otherwise, copy the `post-receive` hook to your Git repository's `/hooks` directory."
3. Converted the tip "The post-receive hook is triggered on every push to the repository." to a line of text inside the instruction.
4. …
=> Update the Git integration doc.

zulip_bots/zulip_bots/bots/define/define.py
=> define: Run html2text as a subprocess
